// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV77fge_fMeOzjA7KolMhULSJdcN3dZH0',
    appId: '1:157253979648:web:a21ad448b07cd4985892e5',
    messagingSenderId: '157253979648',
    projectId: 'gymer-8b429',
    authDomain: 'gymer-8b429.firebaseapp.com',
    storageBucket: 'gymer-8b429.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCee4eLL0bnLdcyayjeWjKli06uKKUL0Gs',
    appId: '1:157253979648:android:5f45a633ae7e36c45892e5',
    messagingSenderId: '157253979648',
    projectId: 'gymer-8b429',
    storageBucket: 'gymer-8b429.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXY6tlqeaiHJJmZslZW8ArvnOCms2NFNc',
    appId: '1:157253979648:ios:744a70b5871ee1cd5892e5',
    messagingSenderId: '157253979648',
    projectId: 'gymer-8b429',
    storageBucket: 'gymer-8b429.appspot.com',
    iosBundleId: 'com.app.gymer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXY6tlqeaiHJJmZslZW8ArvnOCms2NFNc',
    appId: '1:157253979648:ios:744a70b5871ee1cd5892e5',
    messagingSenderId: '157253979648',
    projectId: 'gymer-8b429',
    storageBucket: 'gymer-8b429.appspot.com',
    iosBundleId: 'com.app.gymer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV77fge_fMeOzjA7KolMhULSJdcN3dZH0',
    appId: '1:157253979648:web:e2e569459d1fd4fa5892e5',
    messagingSenderId: '157253979648',
    projectId: 'gymer-8b429',
    authDomain: 'gymer-8b429.firebaseapp.com',
    storageBucket: 'gymer-8b429.appspot.com',
  );
}
